// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMayrZ4lZpD6rZ-i5YCs1y5-D9AtVva6M',
    appId: '1:578912795678:web:4bef14f7cf01cd1235420f',
    messagingSenderId: '578912795678',
    projectId: 'visuo-f0ddc',
    authDomain: 'visuo-f0ddc.firebaseapp.com',
    storageBucket: 'visuo-f0ddc.appspot.com',
    measurementId: 'G-9P3KQSPR8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGGePU99_sju066HvlPICnavBFxH4VYas',
    appId: '1:578912795678:android:7f0a5568e8af3af735420f',
    messagingSenderId: '578912795678',
    projectId: 'visuo-f0ddc',
    storageBucket: 'visuo-f0ddc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_ehew5It99n83k9ExpODFO8lV7g3TZi8',
    appId: '1:578912795678:ios:196aebf38e06a21e35420f',
    messagingSenderId: '578912795678',
    projectId: 'visuo-f0ddc',
    storageBucket: 'visuo-f0ddc.appspot.com',
    iosClientId: '578912795678-9p2m2rhb8vamoi8j3p7gv2vf94h2pmur.apps.googleusercontent.com',
    iosBundleId: 'com.example.hadronSchematicAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_ehew5It99n83k9ExpODFO8lV7g3TZi8',
    appId: '1:578912795678:ios:196aebf38e06a21e35420f',
    messagingSenderId: '578912795678',
    projectId: 'visuo-f0ddc',
    storageBucket: 'visuo-f0ddc.appspot.com',
    iosClientId: '578912795678-9p2m2rhb8vamoi8j3p7gv2vf94h2pmur.apps.googleusercontent.com',
    iosBundleId: 'com.example.hadronSchematicAssistant',
  );
}
